appId: ragDemo

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/actions.response-503: |
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"503","messageBody":"503 Service Unavailable"}}
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/group.name: public
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: 200-404
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  dynamic:
    enabled: true
    nsPrefix: false
    tls: false
    baseDomain: ragdemo.itgix.eu

ingressClassName: "alb"

image: 722377226063.dkr.ecr.eu-west-1.amazonaws.com/rag-demo:26

resources:
  requests:
    memory: "3052Mi"
    cpu: "100m"
    #nvidia.com/gpu: 1  # Request 1 GPU
  limits:
    memory: "3052Mi"
    cpu: "2"
    #nvidia.com/gpu: 1  # Limit to 1 GPU

env:
- name: QDRANT_URL
  value: "http://qdrant-vectordb.qdrant:6333/"
#- name: QDRANT_API_KEY
#  value: "superSecretApiKeyHere"
- name: BUCKET_NAME
  value: itgix-rag-demo 
- name: FRONTEND_DOMAIN
  value: ""
- name: AI_MODEL
  value: "arn:aws:bedrock:us-east-1:722377226063:inference-profile/us.anthropic.claude-3-5-sonnet-20241022-v2:0"

externalsecretEnv:
  enabled: true
  data:
    - secretKey: QDRANT_API_KEY
      remoteRef:
        key: ""
        property: QDRANT_API_KEY


envFromExternalSecret:
  enabled: true
  vars:
    - name: QDRANT_API_KEY
      key: QDRANT_API_KEY


ragdemoCX: true

ragdemoCXimage: 722377226063.dkr.ecr.eu-west-1.amazonaws.com/rag-demo:ver19

ragdemoCXresources:
  requests:
    memory: "3052Mi"
    cpu: "100m"
    #nvidia.com/gpu: 1  # Request 1 GPU
  limits:
    memory: "3052Mi"
    cpu: "2"
    #nvidia.com/gpu: 1  # Limit to 1 GPU

ragdemoCXenv:
- name: BACKEND_URL
  value: "http://rag-demo:8080"