apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: {{ gitops_destination_repo }}
    targetRevision: HEAD
    path: helm/infra-services
    helm:
      valueFiles:
      - values/{{ environment }}/{{ region }}/infra-facts.yaml
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 3
