{{- range .Values.argocdRepositories }}
{{- if and .repoUrl .username .password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" ( .repoUrl | sha1sum ) }}-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .repoUrl | quote }}
  username: {{ .username | quote }}
  password: {{ .password | quote }}
---
{{- end }}
{{- end }}
