{{- if .Values.configuration.enabled }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h0m0s
  limits:
    cpu: 1k
    memory: 1000Gi
  template:
    metadata:
      labels:
        karpenter/provisioner: default
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
      {{- range .Values.configuration.availabilityZones }}
        - {{ . }}
      {{- end }}
      - key: kubernetes.io/arch
        operator: In
        values:
      {{- range .Values.configuration.arch }}
        - {{ . }}
      {{- end }}
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
      {{- range .Values.configuration.capacityType}}
        - {{ . }}
      {{- end }}
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
      {{- range .Values.configuration.instanceSize}}
        - {{ . }}
      {{- end }}
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
      {{- range .Values.configuration.instanceCategory}}
        - {{ . }}
      {{- end }}
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "4"
{{- end }}
