{{- if .Values.ragdemoCX }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.js: |
    window.ENV = {
      WS_URL: "{{ .Values.ragdemoCXvariables.wsUrl }}",
      UPLOAD_URL: "{{ .Values.ragdemoCXvariables.uploadUrl }}"
    };
{{- end }}
