{{- if .Values.ragdemoCX }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-demo-cx
  labels:
    app: rag-demo-cx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-demo-cx
  template:
    metadata:
      labels:
        app: rag-demo-cx
    spec:
      serviceAccountName: ai-service-account
      imagePullSecrets:
      - name: gitlab-itgix-secret
      containers:
      - name: rag-demo-cx
        image: {{ .Values.ragdemoCXimage }}
        command: [ "python3", "main.py" ]  # Added command to run the script
        resources:
{{ toYaml .Values.ragdemoCXresources | indent 10 }}
        ports:
        - containerPort: 8080  # Application's listening port
          protocol: TCP
        env:
{{ toYaml .Values.ragdemoCXenv | indent 10 }}
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
{{- end }}