apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-demo
  labels:
    app: rag-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-demo
  template:
    metadata:
      labels:
        app: rag-demo
    spec:
      serviceAccountName: ai-service-account
      imagePullSecrets:
      - name: gitlab-itgix-secret
      containers:
      - name: gpu-container
        image: {{ .Values.image }}
        command: [ "python3", "main.py" ]  # Added command to run the script
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 8080  # Application's listening port
          protocol: TCP
        env:
{{- range $name, $val := .Values.env }}
        - name: {{ $name }}
          value: {{ $val | quote }}
{{- end }}
{{- range .Values.secretEnv }}
  - name: {{ .name }}
    valueFrom:
      secretKeyRef:
        name: {{ .secretName }}
        key: {{ .secretKey }}
{{- end }}
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-itgix-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIuaXRnaXguY29tOjUwNTAiOnsidXNlcm5hbWUiOiJyYWctZGVtby11c2VyLWRvY2tlciIsInBhc3N3b3JkIjoiZ2xkdC1QQXdmU3plLTZQTVF3X0x1eHRzeSIsImF1dGgiOiJjbUZuTFdSbGJXOHRkWE5sY2kxa2IyTnJaWEk2WjJ4a2RDMVFRWGRtVTNwbExUWlFUVkYzWDB4MWVIUnplUT09In19fQ==
type: kubernetes.io/dockerconfigjson
