apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qdrant-env-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: qdrant-env-secret
    creationPolicy: Owner
  data:
  {{- range .Values.externalsecretEnv.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
  {{- end }}
