apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-itgix-secret
#  annotations:
#     "helm.sh/hook": pre-upgrade
#    "helm.sh/hook-weight": "-5"
#     "helm.sh/hook-delete-policy": before-hook-creation
#     argocd.argoproj.io/sync-wave: "-3"
  labels:
    app: {{ .Values.appId }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gitlab-itgix-secret
    kind: ClusterSecretStore
  target:
    name: gitlab-itgix-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .regcred | toString }}"
    creationPolicy: Owner
    {{- range .Values.externalsecretEnv.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}



