{{- if .Values.ragdemoCX }}
apiVersion: v1
kind: Service
metadata:
  name: rag-demo-cx
  labels:
    app: rag-demo-cx
spec:
  selector:
    app: rag-demo-cx
  ports:
  - protocol: TCP
    port: 8080         # External port
    targetPort: 8080 # Container's listening port
  type: ClusterIP    # Change to NodePort or LoadBalancer as needed
{{- end }}

