{{- if gt (len .Values.jobs) 0 }}
{{- if .Values.cm.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appId }}-job"
  labels:
    app: "{{ .Values.appId }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-2"
data:
{{- tpl (include "env_vars_global" .) . | indent 2 -}}
  {{- range $key, $val := .Values.cm.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- tpl (include "env_vars" .) . | indent 2 -}}
{{- end }}
{{- end }}
