{{- if not .Values.secretEnv.enabled -}}
{{- if .Values.externalsecretEnv.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appId }}-env-secret-job
  labels:
    app: {{ .Values.appId }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appId }}-external-secret-job
    creationPolicy: Owner
  data:
    {{- range .Values.externalsecretEnv.env }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .key }}
        property: {{ .property }}
    {{- end -}}
{{- end }}
{{- end }}
