{{- if gt (len .Values.jobs) 0 }}
{{ if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name }}-job"
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
{{- if .Values.serviceAccount.annotations }}
{{ tpl (toYaml .Values.serviceAccount.annotations) . | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
