infra-services:
  aws_loadbalancer_enabled: true
  external_dns_enabled: true
  external_secrets_enabled: true
  karpenter_enabled: true
  demo_app_enabled: true

  aws_account_id: ~
  region: ~
  eks_cluster_name: ~
  vpc_id: ~
  dns_hosted_zone: ~
