apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.js: |
    window.ENV = {
      WS_URL: "{{ .Values.variables.wsUrl }}",
      UPLOAD_URL: "{{ .Values.variables.uploadUrl }}"
    };