apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-demo-ui
  labels:
    app: rag-demo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-demo-ui
  template:
    metadata:
      labels:
        app: rag-demo-ui
    spec:
      serviceAccountName: ai-service-account
      imagePullSecrets:
      - name: gitlab-itgix-secret
      containers:
      - name: rag-demo-ui
        image: {{ .Values.image }}
        command: [ "python3", "main.py" ]  # Added command to run the script
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 8080  # Application's listening port
          protocol: TCP
        env:
{{ toYaml .Values.env | indent 10 }}
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      volumeMounts:
        - name: config-volume
          mountPath: /app/static/js/config.js
          subPath: config.js
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-itgix-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIuaXRnaXguY29tOjUwNTAiOnsidXNlcm5hbWUiOiJyYWctZGVtby11c2VyLWRvY2tlciIsInBhc3N3b3JkIjoiZ2xkdC1QQXdmU3plLTZQTVF3X0x1eHRzeSIsImF1dGgiOiJjbUZuTFdSbGJXOHRkWE5sY2kxa2IyTnJaWEk2WjJ4a2RDMVFRWGRtVTNwbExUWlFUVkYzWDB4MWVIUnplUT09In19fQ==
type: kubernetes.io/dockerconfigjson
