apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-aws
  namespace: external-secrets-operator
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ index .Values "infra-services" "region" }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator-sa
            namespace: external-secrets-operator
