apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ index .Values "infra-services" "aws_account" }}:role/{{ index .Values "infra-services" "eks_cluster_name" }}-secrets-operator
  name: external-secrets-operator-sa
  namespace: external-secrets-operator