{{- if index .Values "infra-services" "external_secrets_enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: {{ index .Values "infra-services" "gitops_destination_repo" }}
    targetRevision: HEAD
    path: helm/external-secrets-operator
    helm:
      valueFiles:
        - ../external-secrets-operator/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "aws_region" }}/values.yaml
        - ../infra-services/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "aws_region" }}/infra-facts.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
{{- end }}