{{- if index .Values "infra-services" "qdrant_vectordb" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant-vectordb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: {{ index .Values "infra-services" "gitops_destination_repo" }}
    targetRevision: HEAD
    path: helm/qdrant-vectordb
    helm:
      valueFiles:
        - ../qdrant-vectordb/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/values.yaml
        - ../infra-services/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/infra-facts.yaml
      values: |
        qdrant:
          ingress:
            enabled: true
            hosts:
              - host: qdrant-{{ index .Values "infra-services" "environment" }}.{{ index .Values "infra-services" "dns_main_domain" }}
                paths:
                  - path: /
                    pathType: Prefix
                    servicePort: 6333
        externalsecretEnv:
          data:
            - secretKey: password
              remoteRef:
                key: "{{ index .Values "infra-services" "region_short" }}-{{ index .Values "infra-services" "environment" }}-{{ index .Values "infra-services" "project_name" }}-qdrant-env-secret"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
{{- end }}