{{- if index .Values "infra-services" "ragdemo_enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: {{ index .Values "infra-services" "gitops_destination_repo" }}
    targetRevision: HEAD
    path: helm/rag-demo
    helm:
      valueFiles:
        - ../rag-demo/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/values.yaml
        - ../infra-services/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/infra-facts.yaml
      values: |
        ingress:
          hosts:
            - host: ragdemo-{{ index .Values "infra-services" "environment" }}.{{ index .Values "infra-services" "dns_main_domain" }}
            - host: ragdemo-cx-{{ index .Values "infra-services" "environment" }}.{{ index .Values "infra-services" "dns_main_domain" }}
        env:
          BUCKET_NAME: {{ index .Values "infra-services" "project_name" }}-s3-{{ index .Values "infra-services" "region_short" }}-{{ index .Values "infra-services" "environment" }}-rag-demo
          FRONTEND_DOMAIN: ragdemo-cx-{{ index .Values "infra-services" "environment" }}.{{ index .Values "infra-services" "dns_main_domain" }}
          AI_MODEL: "arn:aws:bedrock:us-east-1:{{ index .Values "infra-services" "aws_account_id" }}:inference-profile/us.anthropic.claude-3-5-sonnet-20241022-v2:0"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rag-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
{{- end }}